Add functions to delete all messages from the feed.
DKE-Data/agrirouter-sdk-java pull request #177
Opened 2022-02-11 14:01 UTC by saschadoemer

Format.

2022-02-14 08:38 UTC, Frank-Wiebeler requested changes
Please fix CI first

2022-02-15 18:54 UTC, Frank-Wiebeler reviewed
Just small typos; can be merged after those were fixed.

DRY principle is violated ( createMessageParametersToDeleteAllMessages ); this should maybe be addressed in an additional PR as it is the case with the other 2 PRs as well.


In general:   Awesome work, thank you for your input ヽ(´▽`)/

2022-02-15 18:54 UTC, Frank-Wiebeler commented on agrirouter-sdk-java-api/src/main/java/com/dke/data/agrirouter/api/service/messaging/http/DeleteMessageService.java
> +   * intervall of 4 weeks (which is the maximum of time the messages are stored within the
-l (interval)

2022-02-15 18:54 UTC, Frank-Wiebeler commented on agrirouter-sdk-java-api/src/main/java/com/dke/data/agrirouter/api/service/messaging/http/DeleteMessageService.java
> +   * intervall of 4 weeks (which is the maximum of time the messages are stored within the
-l ;)

2022-02-15 18:54 UTC, Frank-Wiebeler commented on agrirouter-sdk-java-api/src/main/java/com/dke/data/agrirouter/api/service/messaging/mqtt/DeleteMessageService.java
> +   * intervall of 4 weeks (which is the maximum of time the messages are stored within the
-l ;)

2022-02-15 18:54 UTC, Frank-Wiebeler commented on agrirouter-sdk-java-api/src/main/java/com/dke/data/agrirouter/api/service/messaging/mqtt/DeleteMessageService.java
> +   * intervall of 4 weeks (which is the maximum of time the messages are stored within the
-l ;)

2022-02-16 14:37 UTC, saschadoemer commented
> Just small typos; can be merged after those were fixed.
> 
> DRY principle is violated ( createMessageParametersToDeleteAllMessages ); this should maybe be addressed in an additional PR as it is the case with the other 2 PRs as well.
> 
> In general: Awesome work, thank you for your input ヽ(´▽`)/

Fixed the DRY problem with a default implementation on the interface. Not quite sure about the abstraction overhead.

2022-02-21 21:55 UTC, Frank-Wiebeler approved these changes
Awesome as always 🥳

2022-02-21 21:55 UTC, merged